import { Lead, Property } from './types';

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    phone: '+91 98765 43210',
    email: 'rajesh.kumar@email.com',
    source: 'Website',
    status: 'New Lead',
    assignedAgent: 'Amit Sharma',
    createdAt: new Date('2024-03-08'),
    budget: '₹50-70 Lakhs',
    requirements: 'Looking for 2BHK in North Delhi',
  },
  {
    id: '2',
    name: 'Priya Mehta',
    phone: '+91 98765 43211',
    email: 'priya.mehta@email.com',
    source: 'WhatsApp',
    status: 'Contacted',
    assignedAgent: 'Neha Gupta',
    createdAt: new Date('2024-03-07'),
    budget: '₹80-100 Lakhs',
    requirements: 'Looking for 3BHK with parking',
  },
  {
    id: '3',
    name: 'Arjun Patel',
    phone: '+91 98765 43212',
    source: 'Phone',
    status: 'Requirement Collected',
    assignedAgent: 'Amit Sharma',
    createdAt: new Date('2024-03-06'),
    budget: '₹40-60 Lakhs',
    requirements: '2BHK near metro station',
  },
  {
    id: '4',
    name: 'Sneha Singh',
    phone: '+91 98765 43213',
    email: 'sneha.singh@email.com',
    source: 'Social Media',
    status: 'Property Suggested',
    assignedAgent: 'Rahul Verma',
    createdAt: new Date('2024-03-05'),
    budget: '₹1-1.5 Cr',
    requirements: '4BHK luxury apartment',
  },
  {
    id: '5',
    name: 'Vikram Reddy',
    phone: '+91 98765 43214',
    source: 'Website',
    status: 'Visit Scheduled',
    assignedAgent: 'Neha Gupta',
    createdAt: new Date('2024-03-04'),
    budget: '₹60-80 Lakhs',
    scheduledVisit: {
      date: '2024-03-12',
      property: 'Skyline Residency',
    },
  },
  {
    id: '6',
    name: 'Anita Desai',
    phone: '+91 98765 43215',
    email: 'anita.desai@email.com',
    source: 'WhatsApp',
    status: 'Visit Completed',
    assignedAgent: 'Amit Sharma',
    createdAt: new Date('2024-03-03'),
    budget: '₹70-90 Lakhs',
    notes: 'Very interested, waiting for loan approval',
  },
  {
    id: '7',
    name: 'Karan Malhotra',
    phone: '+91 98765 43216',
    source: 'Phone',
    status: 'Booked',
    assignedAgent: 'Rahul Verma',
    createdAt: new Date('2024-03-01'),
    budget: '₹85 Lakhs',
    notes: 'Booked unit 402 at Green Valley',
  },
  {
    id: '8',
    name: 'Deepika Rao',
    phone: '+91 98765 43217',
    source: 'Social Media',
    status: 'Lost',
    assignedAgent: 'Neha Gupta',
    createdAt: new Date('2024-02-28'),
    budget: '₹50 Lakhs',
    notes: 'Found property through another agent',
  },
  {
    id: '9',
    name: 'Suresh Nair',
    phone: '+91 98765 43218',
    email: 'suresh.nair@email.com',
    source: 'Website',
    status: 'New Lead',
    assignedAgent: 'Amit Sharma',
    createdAt: new Date('2024-03-08'),
  },
  {
    id: '10',
    name: 'Kavita Joshi',
    phone: '+91 98765 43219',
    source: 'WhatsApp',
    status: 'Contacted',
    assignedAgent: 'Rahul Verma',
    createdAt: new Date('2024-03-07'),
    budget: '₹45-55 Lakhs',
  },
];

export const mockProperties: Property[] = [
  { id: '1', name: 'Skyline Residency', location: 'North Delhi' },
  { id: '2', name: 'Green Valley Apartments', location: 'South Delhi' },
  { id: '3', name: 'Horizon Heights', location: 'Gurgaon' },
  { id: '4', name: 'Palm Grove', location: 'Noida' },
  { id: '5', name: 'Royal Towers', location: 'East Delhi' },
  { id: '6', name: 'Serene Meadows', location: 'Faridabad' },
];
